# Paths to files (relative to project root or absolute)
json.patients=out/patients.json
yaml.patients=out/patients.yaml
json.doctors=out/doctors.json
yaml.doctors=out/doctors.yaml

# test data count
test.data.count=4
